### PR TITLE
Add MicroPython implementation

### PR DESCRIPTION
**Pull request by rroemhild**

### CODE REVIEW

**Comment by timpur** [comment]
why 'WIP' ?

**Comment by rroemhild** [comment]
It's not that stable we want it to be. But it can be used right now. I think for the issues we see, we can add a know issue topic to our README.md.

**Comment by timpur** [comment]
Okay sounds good

**Comment by rroemhild** [comment]
Known Issue section and the reference to Homie v2.1.0 were added. Free to merge.

**Pull request merged**
